services:
  - docker

before_install:
- docker build --tag=myimage .
- docker run -d --name myimage -v $(pwd):/travis -w /travis myimage:latest tail -f /dev/null
- docker ps

script:
- docker exec -t myimage bash -c python screen.py 
