language: python

services:
  - docker

before_install:
- docker build --tag=myimage .
- docker ps -a
- docker run --rm -it myimage /bin/bash

script:
- docker exec -t myimage bash -c "python screen.py"
