services:
  - docker

before_install:
- docker build --tag=myimage .
- docker run -d --name myimage -v $(pwd):/user/baur myimage:latest tail -f /dev/null
- docker ps

script:
- docker exec -t myimage bash -c "ls -alh"
- docker exec -t myimage bash -c "pwd"
# - docker exec -t myimage bash -c "python -v"
- docker exec -t myimage bash -c "python screen.py" 
